# Generated by Django 4.1.2 on 2022-10-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=64)),
                ("records", models.IntegerField()),
                ("task_id", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ClientTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=64)),
                ("records", models.IntegerField()),
                ("task_id", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ClientTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=128)),
                ("table", models.CharField(max_length=32)),
                ("host", models.CharField(max_length=32)),
                ("port", models.IntegerField()),
                ("results", models.IntegerField()),
                ("runtime", models.IntegerField()),
                ("status", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Cucoo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_data", models.CharField(max_length=128)),
                ("statsh_data", models.CharField(max_length=128)),
                ("hash_idx", models.IntegerField()),
            ],
        ),
    ]
