# Generated by Django 4.1.2 on 2022-10-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intersect", "0012_stash_delete_statsh_rename_table_data_cucoo_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cucoo", name="idx", field=models.IntegerField(null=True),
        ),
    ]
