# Generated by Django 4.1.2 on 2022-10-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intersect", "0013_alter_cucoo_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cucoo",
            name="data",
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="cucoo",
            name="idx",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stash",
            name="data",
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
