# Generated by Django 4.1.2 on 2022-10-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intersect", "0014_alter_cucoo_data_alter_cucoo_idx_alter_stash_data"),
    ]

    operations = [
        migrations.DeleteModel(name="Cucoo",),
        migrations.DeleteModel(name="Stash",),
    ]
