# Generated by Django 4.1.2 on 2022-10-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intersect", "0015_delete_cucoo_delete_stash"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=64)),
                ("h1", models.CharField(max_length=256)),
                ("h2", models.CharField(max_length=256)),
                ("h3", models.CharField(max_length=256)),
            ],
        ),
    ]
