# Generated by Django 4.1.2 on 2022-10-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intersect", "0016_simplehash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplehash", name="h1", field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="simplehash", name="h2", field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="simplehash", name="h3", field=models.CharField(max_length=300),
        ),
    ]
